import os
from dotenv import load_dotenv

load_dotenv()

# Режим работы
TESTNET = os.getenv("TESTNET", "True").lower() == "true"

# API-ключи
API_KEY = os.getenv("BYBIT_API_KEY")
API_SECRET = os.getenv("BYBIT_API_SECRET")

# Торговые пороги (из ТЗ)
ADX_TREND_THRESHOLD = 22
ADX_FLAT_THRESHOLD = 20
BB_WIDTH_MIN_PCT = 2.5
AMPLITUDE_CV_MAX = 40.0
TOUCHES_MIN = 2
EMA_CHANGE_MAX = 2.0
ATR_DECAY_THRESHOLD = 1.5
ATR_PERIOD = 14
ATR_CANDLES_DECAY = 2
TRAILING_STOP_PCT = 15.0
MAX_DRAWDOWN_GLOBAL = 20.0   # будет переопределено в params
COOLDOWN_HOURS = 1
GRID_LEVELS_MIN = 5
CAPITAL_RESERVE = 0.95

# Таймфреймы
TIMEFRAME_PRIMARY = "240"
TIMEFRAME_CONFIRM = "60"

# Параметры управления капиталом
MAX_POSITIONS = 3
CAPITAL_PER_POSITION_PCT = 0.33
LEVERAGE = 1
MARGIN_MODE = "ISOLATED"

# Комиссии и проскальзывание
TAKER_FEE = 0.0004
SLIPPAGE = 0.0002

# ========== Новая стратегия Bollinger + Donchian ==========
BB_PERIOD = 20
BB_STD = 2.0
DONCHIAN_PERIOD = 20
FAST_BREAKOUT_RATIO = 0.7
USE_CONTEXT_FILTER = False
FLAT_MODE = 'breakout_single'
TREND_EMA_PERIOD = 200
USE_TREND_DIRECTION_FILTER = False
USE_VOLATILITY_DECAY_FILTER = False
MAX_CONCURRENT_POSITIONS = 5
RISK_PER_POSITION_PCT = 3.0
COOLDOWN_HOURS_BB_DONCHIAN = 4
MAX_TOTAL_RISK_PERCENT = 15.0