# config/pairs.yaml
BTCUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 300
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 2500
  ENTRY_TOLERANCE_USD: 50
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 8.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 90.0
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

ETHUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 20
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 200
  ENTRY_TOLERANCE_USD: 20
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 30.0
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

SOLUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 0.6
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 4.9
  ENTRY_TOLERANCE_USD: 0.01
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 4.9
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 0.2
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

LINKUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 0.08
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 0.65
  ENTRY_TOLERANCE_USD: 0.02
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 0.15
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

AVAXUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 0.05
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 0.2
  ENTRY_TOLERANCE_USD: 0.02
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 0.144
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

ARBUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 0.0026
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 0.00864
  ENTRY_TOLERANCE_USD: 20
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 0.001
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

DOGEUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 0.0008
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 0.006
  ENTRY_TOLERANCE_USD: 0.0007
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 0.001
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

APTUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 0.01
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 0.06
  ENTRY_TOLERANCE_USD: 20
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 0.01
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0

FILUSDT:
  N: 7
  MIN_BODY_RATIO: 0.3
  DELTA_PRICE: 0.01
  MIN_DISTANCE_BARS: 5
  MAX_DELTA_EXTREMES: 0.06
  ENTRY_TOLERANCE_USD: 20
  MIN_BARS_AFTER_POINT2: 3
  MAX_BARS_AFTER_POINT2: 7
  MAX_LOSS_PER_TRADE: 3.0
  MAX_STOP_DISTANCE_PERCENT: 2.5
  MAX_POSITION_PERCENT: 95.0
  MIN_POSITION_USDT: 10.0
  ACTIVATION_PROFIT_USD: 0.01
  TRAILING_PRICE1: 0
  TRAILING_PRICE2: 0